### ISSUE TITLE
Auto versioning & publishing

### ISSUE THREAD

**Issue by amannn** [molindo/molindo-pipelines#1]
@sfussenegger I thought about a workflow for automating the version number of libraries and publishing them to a registry.

Given a version `0.0.2` in master, it could work like this:

1. First commit in a feature branch.
  a. The version is updated to `0.0.3-SFM-999-branch-description.53a9994`, where the last part is a git hash. The dash after the patch number indicates that it's a pre-release [according to semver](http://semver.org/#spec-item-9).
  b. Publish the package, but don't commit the version.
2. Second commit in the branch.
  a. Same procedure as before, but with a different git hash as npm modules need to have a unique version number and can't be re-published.
3. Merge in master.
  a. The patch version is incremented, thus the new version is `0.0.3`.
  b. Publish the package.
  c. Commit the new version with `[skip ci]` in the commit message in order to avoid another build.

Some thoughts:
 - Automatically updating dependencies could also be done when merging into master if we want to add that in the future.
 - Incrementing minor and major versions happens after approval of a PR if necessary.
 - There will never be a version with `0` as the patch version in master. Not really a big deal though I guess – or did you solve this with the versioning of Java libraries?

What do you think? If this is ok, I can make a PR that adds a script for this workflow.

**Comment by sfussenegger** [comment]
here's what we do with our Jave/Maven CI deployments:

1. never keep release versions in master, use a WIP identifier (in Maven that's always `SNAPSHOT`, e.g. `0.0.1-SNAPSHOT`)
2. use Bamboo build numbers as patch versions (actually less than ideal, but works), keep placeholder in master (we use `9999`, i.e. `0.0.9999-SNAPSHOT`)
3. major and minor versions are updated manually whenever semver rules require it
4. set release versions as part of build and push tag (to re-run a deployment of a certain version, checkout tag `${version}`, set version to `${versions}` and run deployment)

in comparison, the standard Maven release plugin does the following:

1. keep `SNAPSHOT` version in repo (e.g. `0.0.1-SNAPSHOT`)
2. update version to release version (e.g. `0.0.1`)
3. commit change
4. build and release
5. update version to next snapshot (e.g. `0.0.2-SNAPSHOT`)
6. commit change
7. push changes

our approach intentionally avoids commits and branches as either makes it cumbersome to work (e.g. need to merge changes into feature branches after every build)

so with that in mind, some thoughts (no particular order):

* the version in the repo doesn't necessarily have to be the version of the release
* git hashes in versions aren't really helpful as they can't be ordered. if a unique sortable value is needed, timestamps offer a better option - also allowing for multiple releases of the same commit. git tags are a better way to associate releases to commits
* managing the version for CI can and should be mostly automatic. determining the version for release really is the challenge

speaking of determining the versions for release, here's what we do for our Java builds. First we determine if branch is the default branch (typically `master` but there could be other, e.g. `1.x` for old major version support)

* branch is a default branch: reuse major and minor from repo, determine next patch version (`${currentMajor}.${currentMinor}.${nextPatch}`)
* branch is a feature branch: reuse major, minor and patch (`{currentMajor}.${currentMinor}.${currentPatch}-${branchName}.${timestamp}`)

`${nextPatch}` should be `${previousPatch} + 1` but that's not always easy and typically requires either a counter kept by the build system or querying the repository. Generally `${previousPatch} > ${nextPatch}` is easier to determine.

with that said, let's talk next week on how to continue
